services:
  rtstt:
    build:
      context: .
      target: gpu # or cpu
    image: rtstt
    container_name: rtstt
    volumes:
      - ./RealtimeSTT:/app/RealtimeSTT
      - ./example_browserclient:/app/example_browserclient
      - cache:/root/.cache
    environment:
      - RTSTT_LANG=ja
      - RTSTT_RT_MODEL=small
      - RTSTT_MODEL=large-v3
      # - RTSTT_MODEL=deepdml/faster-whisper-large-v3-turbo-ct2
    ports:
      - "9001:9001"

    # if 'gpu' target
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8081:80"
    volumes:
      - ./example_browserclient:/usr/share/nginx/html

volumes:
  cache: